# Generated by Django 3.2 on 2024-02-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueños',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('raza', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=20)),
                ('tratamiento', models.CharField(choices=[('CM', 'consulta medica'), ('UR', 'Urgencia'), ('OB', 'Observacion regular'), ('TQ', 'Tratamiento quirurgico'), ('SO', 'Sin observacines')], default='SO', max_length=2)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.dueños')),
            ],
        ),
    ]
