# Generated by Django 3.2 on 2024-02-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_animales_tratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroconsultas',
            name='dni_dueño',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroconsultas',
            name='dueño',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
