# Generated by Django 3.2 on 2024-02-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240204_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroconsultas',
            name='dni_dueño',
        ),
        migrations.AlterField(
            model_name='registroconsultas',
            name='dueño',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
