# Generated by Django 3.2 on 2024-02-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20240204_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userMail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('fullname', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
