# Generated by Django 5.0.2 on 2024-03-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_adminusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnosClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(max_length=20)),
                ('consulta', models.CharField(choices=[('CM', 'consulta medica'), ('UR', 'Urgencia'), ('OB', 'Observacion regular'), ('TQ', 'Tratamiento quirurgico'), ('SO', 'Sin observacines')], default='SO', max_length=2)),
            ],
        ),
    ]
